packages:
  - .

allowBuilds:
  '@swc/core': true
  cbor-extract: false
  esbuild: true

ignoredBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - sharp

minimumReleaseAgeExclude:
  - nanoid@6.0.0
  - postcss@8.5.17

onlyBuiltDependencies:
  - esbuild
